### ISSUE TITLE
Inconsistent type for `Domain.current_zone`

### ISSUE THREAD

**Issue by ghost** [happyDomain/ansible-collection#1]
`Domain.current_zone()` is [defined in `python-sdk/happydomain/domain.py`](https://github.com/happyDomain/python-sdk/blob/7325b3956bda25f1d67730ea2780250791c8fd1d/happydomain/domain.py#LL29C1-L34C36) as:

```py
class Domain:

    @property
    def current_zone(self):
        if len(self.zone_history) == 0:
            self.import_zone()

        return self.zone_history[0]
```

This method is used is used in many places across the collection ([1](https://github.com/happyDomain/ansible-collection/blob/9b25bd841292cc21cb0073334c6982da7d924ad2/plugins/modules/domain.py#L62), [2](https://github.com/happyDomain/ansible-collection/blob/9b25bd841292cc21cb0073334c6982da7d924ad2/plugins/modules/domain.py#L65) and [3](https://github.com/happyDomain/ansible-collection/blob/9b25bd841292cc21cb0073334c6982da7d924ad2/plugins/modules/domain.py#L79)) to access the ID of the zone: `domain.current_zone.id`. However, as reported in happyDomain/python-sdk#1, the `Domain.zone_history` type is inconsistent and using the `happydns.happydomain.domain` module results in this error: `AttributeError: 'str' object has no attribute`.

**Comment by nemunaire** [comment]
The inconsistency has been resolved directly in the SDK: https://github.com/happyDomain/python-sdk/issues/1

Could you please test that you no longer have any `AttributeError: 'str' object has no attribute`?
